import '../globals.scss'

export const metadata = {
  title: 'Text Opacity On Scroll',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
